FROM antaeus-base 

MAINTAINER wangrupeng wangrupeng@live.cn

EXPOSE 28888

MAINTAINER wangrupeng wangrupeng@live.cn

COPY Antaeus /home/Antaeus

CMD ./home/Antaeus/start.sh -start

WORKDIR /home/Antaeus



